import 'package:flutter/foundation.dart';
import '../../models/project_model.dart';
import '../../repositories/project_repository.dart';
import 'dart:math';

/// Controller untuk mengelola data proyek pada sisi dosen.
class ProjectController extends ChangeNotifier {
  final ProjectRepository _repository;

  List<ProjectModel> projects = [];
  bool isLoading = false;
  String? errorMessage;

  ProjectController(this._repository);

  /// Mengambil daftar proyek dari repository dan memperbarui state.
  Future<void> fetchProjects() async {
    isLoading = true;
    errorMessage = null;
    notifyListeners();

    try {
      projects = await _repository.getProjects();
    } catch (e) {
      errorMessage = e.toString();
    } finally {
      isLoading = false;
      notifyListeners();
    }
  }

  /// Membuat proyek baru dengan kode bergabung otomatis.
  Future<void> createProject(String lecturerId, String title, String description, String? submissionInfo) async {
    isLoading = true;
    errorMessage = null;
    notifyListeners();

    try {
      final joinCode = _generateJoinCode();
      final newProject = ProjectModel(
        id: '', // Will be generated by Supabase
        lecturerId: lecturerId,
        title: title,
        description: description,
        joinCode: joinCode,
        finalSubmissionInfo: submissionInfo,
      );
      
      final createdProject = await _repository.createProject(newProject);
      projects.add(createdProject);
    } catch (e) {
      errorMessage = e.toString();
    } finally {
      isLoading = false;
      notifyListeners();
    }
  }

  /// Menghasilkan 6 karakter kode acak untuk bergabung ke proyek.
  String _generateJoinCode() {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
    final rnd = Random();
    return String.fromCharCodes(Iterable.generate(6, (_) => chars.codeUnitAt(rnd.nextInt(chars.length))));
  }
}
